return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "awk-language-server",
      "bash-language-server",
      "clang-format",
      "clangd",
      "codelldb",
      "css-lsp",
      "debugpy",
      "detekt",
      "docker-language-server",
      "elixir-ls",
      "elp",
      "expert",
      "html-lsp",
      "jdtls",
      "js-debug-adapter",
      "json-lsp",
      "julia-lsp",
      "kotlin-lsp",
      "ktlint",
      "lua-language-server",
      "oxfmt",
      "oxlint",
      "rumdl",
      "rust-analyzer",
      "shellcheck",
      "taplo",
      "ty",
      "vtsls",
      "wasm-language-tools",
      "yaml-language-server",
      "yamllint",
    },
  },
}
